import copy
import xml.etree.ElementTree as ET
from pathlib import Path
from zipfile import ZipFile, ZIP_DEFLATED

SRC = Path(r"c:\Users\Nishchay Rai S\Downloads\Autoencoder.docx")
OUT = Path(r"c:\Users\Nishchay Rai S\OneDrive\Desktop\Major Project\perturbo\perturbo_streamlit\Autoencoder_updated.docx")
NS = {"w": "http://schemas.openxmlformats.org/wordprocessingml/2006/main"}
W = "{%s}" % NS["w"]
XMLNS = "{http://www.w3.org/XML/1998/namespace}space"


def get_text(paragraph):
    return "".join(t.text or "" for t in paragraph.iter(W + "t")).strip()


def set_text(paragraph, text):
    ppr = None
    for child in list(paragraph):
        if child.tag == W + "pPr":
            ppr = copy.deepcopy(child)
        paragraph.remove(child)
    if ppr is not None:
        paragraph.append(ppr)
    if text:
        run = ET.SubElement(paragraph, W + "r")
        t = ET.SubElement(run, W + "t")
        if text.startswith(" ") or text.endswith(" "):
            t.set(XMLNS, "preserve")
        t.text = text


def replace_range(paragraphs, start_idx, end_idx, new_paragraphs):
    rng = list(range(start_idx, end_idx + 1))
    for offset, idx in enumerate(rng):
        text = new_paragraphs[offset] if offset < len(new_paragraphs) else ""
        set_text(paragraphs[idx], text)


def main():
    with ZipFile(SRC, "r") as zin:
        files = {name: zin.read(name) for name in zin.namelist()}

    doc = ET.fromstring(files["word/document.xml"])
    paragraphs = list(doc.iter(W + "p"))
    texts = [get_text(p) for p in paragraphs]

    for i, text in enumerate(texts):
        if text.startswith("Customer sentiments are exploited in various applications"):
            set_text(
                paragraphs[i],
                "Online review systems are widely used for sentiment understanding, rating prediction, and decision support, but such systems can be affected by small linguistic changes that alter model behavior. Adversarial and perturbed text in NLP has therefore become an important research problem, especially in systems where subtle token substitutions, paraphrases, misspellings, and semantically influential modifiers may change the model output [10]-[19]. This project presents an explainable review-analysis system that detects whether a review is clean or perturbed and also predicts its star rating. The system combines semantic representation, autoencoder-based anomaly signals, adverb-focused linguistic features, and machine learning models in a single framework. The implementation uses semantic embeddings together with hybrid features such as reconstruction error, latent distance, anomaly score, adverb count, adverb weight, and average adverb influence. Reconstruction-based anomaly ideas are motivated by recent work on calibrated and layer-wise autoencoder detection methods, which show that abnormal samples can be identified through feature reconstruction behavior [3], [7], [9]. The project also includes an interactive dashboard that provides multiple explanation views, such as SHAP/LIME-based interpretation, adverb ablation analysis, counterfactual explanations, token sensitivity, calibration, and feature-level response analysis. The main contribution of the project is that it does not stop with prediction alone. Instead, it provides a transparent explanation of why a review is classified as clean or perturbed and how specific linguistic choices influence the result. In this way, the project supports the larger research direction of interpretable and trustworthy NLP systems for perturbed text analysis [18], [19].",
            )
            break

    replace_range(
        paragraphs,
        411,
        448,
        [
            "Online reviews have become a major source of information for both users and businesses. Customers use reviews to compare products, services, hotels, restaurants, and other offerings, while organizations use reviews to understand satisfaction, identify problems, and improve decisions. Because of this, natural language processing and machine learning are widely used for sentiment analysis, classification, and rating prediction. However, existing systems are often sensitive to small linguistic changes, which makes robustness and interpretability important research problems [18].",
            "A major challenge in review analysis is that small changes in wording can change the output of a model even when the overall topic remains similar. In adversarial NLP literature, this has been shown through synonym substitution attacks, contextual replacement attacks, misspellings, trigger phrases, and token-level perturbations [10]-[17]. In real review text, similar effects may happen through ordinary language variation, especially when users use intensifiers, negations, contrastive phrases, or exaggerated wording. As a result, it is not always enough for a system to produce only a prediction. It must also explain why the prediction changed and whether the wording itself contributed to the output.",
            "This project is built on that motivation. Instead of treating every review as a normal sentiment input, the system attempts to identify whether the review is clean or perturbed. In this work, a perturbed review does not always mean malicious text; rather, it refers to a review whose wording shows unusual or semantically influential characteristics that may affect how the model behaves. The broader literature shows that detectors based only on surface statistics may not be sufficient, and that stronger methods often rely on multiple signals, robust feature spaces, and reconstruction-based behavior [1]-[3], [7].",
            "Another limitation in many review-analysis systems is the lack of interpretability. A model may label a review as suspicious or perturbed, but the user is often left without a clear explanation of which words or features caused the output. This issue has motivated the development of more robust detectors, calibration-aware systems, purification methods, and autoencoder-based mechanisms in recent research [3], [5], [6], [18]. The current project takes a more explanation-oriented approach by combining perturbation detection with a dashboard that reveals the effect of different features and linguistic elements.",
            "The project therefore has two linked goals: first, to classify whether a review is clean or perturbed and predict the corresponding star rating; second, to explain the reasoning behind the result. The system uses embeddings and hybrid features, including reconstruction error and adverb-based influence, so that the final output is based not only on raw text but also on anomaly-aware signals. This follows the broader trend in the literature where feature-space behavior and model sensitivity are treated as important indicators of adversarial or perturbed input [2], [3], [7], [9].",
            "In summary, the project contributes to the area of trustworthy NLP by building a practical review-analysis system that combines perturbation detection, rating prediction, and explanation. Rather than focusing only on model performance, it also emphasizes transparency, which is increasingly important in modern adversarial and robustness research [18], [19].",
        ],
    )

    replace_range(
        paragraphs,
        534,
        609,
        [
            "This chapter describes the software and hardware requirements needed for the project, defines the problem addressed by the system, presents the objectives, and explains the methodology followed in implementation. The project is developed as an explainable review analysis system that identifies whether a review is clean or perturbed and also predicts the corresponding star rating. Along with prediction, the system provides explanations through multiple XAI methods such as SHAP, LIME, adverb ablation, counterfactual analysis, token attribution, PDP/ICE plots, and calibration output. The need for such systems is motivated by recent work on adversarial and perturbed text, where subtle changes in wording can strongly influence classification behavior [10]-[19].",
            "3.1 SOFTWARE REQUIREMENTS",
            "The project is implemented using Python because it provides strong support for machine learning, natural language processing, deep learning, and visualization. Python also supports a large number of open-source libraries that make development easier and more flexible. The software stack is chosen so that semantic representation, reconstruction-based analysis, and interpretability modules can be integrated within one environment.",
            "The main software requirement is Python 3.10 or above. The project uses NumPy and Pandas for numerical and tabular processing, scikit-learn for classification models, and joblib for loading trained models. Semantic representation is handled through the Transformers library, while PyTorch is used to run the autoencoder. The use of reconstruction-based anomaly signals is aligned with current research that highlights reconstruction and latent behavior as useful indicators of perturbed inputs [3], [7], [9].",
            "The project also uses spaCy for linguistic analysis, especially for identifying adverbs and related tokens. The text normalization process is supported by helper libraries such as ftfy and unidecode. For boosting-based classification, the project uses XGBoost and LightGBM. SHAP and LIME are used for explanation, Plotly for charts, and Streamlit for the final dashboard interface.",
            "The major software requirements are:",
            "Operating System: Windows 10/11 or Ubuntu/Linux",
            "Programming Language: Python 3.10 or above",
            "Development Tools: VS Code / Jupyter Notebook",
            "Libraries and Frameworks: Streamlit, PyTorch, Transformers, NumPy, Pandas, scikit-learn, joblib, spaCy, ftfy, unidecode, XGBoost, LightGBM, SHAP, LIME, and Plotly.",
            "These software tools are sufficient to develop, run, and visualize the outputs of the project.",
            "3.2 HARDWARE REQUIREMENTS",
            "The hardware requirements of the project are moderate because the system mainly performs inference using already trained models. However, since the project handles semantic embeddings, machine learning models, autoencoder features, and interactive dashboard visualizations, a system with reasonable processing power and memory is needed.",
            "A laptop or desktop with an Intel i5/i7 processor or AMD Ryzen 5/7 processor is suitable for running the project. A minimum of 8 GB RAM is needed, while 16 GB RAM is recommended for smoother execution. SSD storage is preferred because it provides faster loading of models, datasets, and the virtual environment.",
            "A GPU is not compulsory for the current implementation because the dashboard can run on CPU. However, GPU support can be helpful if the project is extended for larger model training or stronger adversarial evaluation in the future.",
            "The required hardware specifications are: Processor: Intel Core i5/i7 or AMD Ryzen 5/7; RAM: Minimum 8 GB, Recommended 16 GB; Storage: Minimum 256 GB SSD, Recommended 500 GB SSD; GPU: Optional; Internet Connection: Required during installation and setup; Display: Standard laptop/desktop display for dashboard visualization.",
            "These hardware requirements are enough to run the project efficiently and demonstrate the dashboard outputs in real time.",
            "3.3 PROBLEM STATEMENT",
            "Online review platforms are widely used for customer feedback, product evaluation, and service analysis. Machine learning and NLP models are commonly applied to classify reviews, detect sentiment, and predict ratings. However, these models are often sensitive to small linguistic variations. Minor changes in wording, such as adverbs, intensifiers, negations, or unusual phrasing, can affect the output of the model even when the main topic of the sentence remains similar. This challenge is well supported by adversarial text research, which shows that perturbations can significantly alter classifier behavior [10]-[17].",
            "Most existing systems focus only on prediction accuracy and provide very little explanation about why a review was classified in a particular way. Because of this, users may not understand whether the output was influenced by semantic irregularity, unusual sentence structure, or a small but important word-level change. This creates a lack of transparency and trust.",
            "The problem addressed in this project is to build an explainable review analysis system that can identify whether a review is clean or perturbed, predict the corresponding star rating, detect the influence of semantically important adverbs and linguistic variations, and explain the prediction in an understandable way.",
            "The system should not only give a final result, but also provide supporting evidence that helps users understand why the result was produced.",
            "3.4 OBJECTIVES",
            "The objectives of the project are as follows:",
            "To develop a review analysis system that identifies whether an input review is clean or perturbed.",
            "To generate semantic and hybrid features such as embeddings, reconstruction error, anomaly score, and adverb-based influence for prediction.",
            "To predict the corresponding star rating of the review using trained machine learning models.",
            "To provide explainable outputs through methods such as SHAP, LIME, adverb ablation, counterfactual analysis, token attribution, and other dashboard visualizations.",
            "These objectives ensure that the system is not limited to prediction alone, but also includes interpretability, trust, and usability.",
            "3.5 METHODOLOGY",
            "The methodology of the project consists of several stages, beginning with text input and ending with explainable dashboard output. In the first stage, the review text is entered by the user through the dashboard and normalized for further processing. In the second stage, the normalized review is passed through the E5 embedding model, which converts the review into a dense semantic vector representation.",
            "In the third stage, the embedding is processed using the autoencoder. The autoencoder reconstructs the embedding and produces reconstruction error and latent distance. These values are used to measure how unusual the review is compared to the normal review patterns seen in training. This use of reconstruction-based anomaly behavior is consistent with recent autoencoder-centered detection work [3], [7], [9].",
            "In the fourth stage, linguistic analysis is applied using spaCy. The system detects adverbs and intensifiers in the review. Each adverb is removed one by one, and the semantic difference between the original sentence and the modified sentence is measured. From this, the project computes adverb count, adverb weight, average adverb influence, and identifies the dominant adverb.",
            "In the fifth stage, the embedding and hybrid features are combined into one feature vector. This feature vector is passed into multiple trained classification models such as Logistic Regression, SVM, Random Forest, XGBoost, and LightGBM. These models classify the review as clean or perturbed. At the same time, separate rating models predict the star rating.",
            "In the sixth stage, explainability methods are applied. SHAP is used to identify how individual features contribute to the final classification. LIME provides a local explanation around the current input. Adverb ablation analysis shows how the probability changes when adverbs are removed. Counterfactual analysis shows the minimal text change that alters prediction confidence. Token attribution identifies the words with the highest effect on prediction. PDP/ICE plots visualize how selected hybrid features influence output probability. Calibration curves and model agreement are also generated to improve trust in the system. In the final stage, all outputs are displayed in the Streamlit dashboard.",
            "The methodology therefore combines semantic embeddings, anomaly-aware features, linguistic analysis, machine learning models, and explainable AI into a single integrated framework for review analysis. This design is consistent with recent research that encourages hybrid, interpretable, and robustness-aware approaches for perturbed text [1], [2], [18], [19].",
        ],
    )

    for idx, text in {
        620: "The system design of the project focuses on creating an explainable review analysis pipeline that can process review text, identify perturbations, predict ratings, and generate interpretable outputs. The entire workflow is organized in a step-by-step manner so that the review moves from data collection and preprocessing to feature extraction, prediction, and final visualization. This helps in understanding both the structure and operation of the system clearly. The design reflects current work on perturbation-aware detection, where systems benefit from multiple signals, reconstruction-based cues, and robust analysis pipelines [1]-[3], [7].",
        624: "The overall architecture of the proposed system is shown in Fig. 4.1. The system starts with review collection, where TripAdvisor reviews are used as the input data source. The reviews are then passed to the preprocessing stage, where the text is cleaned, normalized, and tokenized. This step ensures that the input becomes suitable for semantic analysis and downstream prediction tasks.",
        625: "In the next stage, feature extraction is performed. Semantic embeddings are generated from the processed review text, and the autoencoder is trained to learn reconstruction-based patterns from the embeddings. These features are useful for identifying unusual or perturbed review behavior. This design is supported by recent work on calibrated and layer-wise reconstruction-based detectors [3], [7], [9]. After this, the extracted features are given to machine learning models for detection and prediction. In this project, models such as Logistic Regression, Support Vector Machine, Random Forest, and Gradient Boosting are used for classification. The final stage is evaluation and visualization, where model outputs are converted into graphs, metrics, and interpretable dashboard results. The complete system architecture and workflow are illustrated in Fig. 4.1.",
        637: "The data flow of the proposed system can also be understood from Fig. 4.1, since the same figure shows how the review moves through each stage of the pipeline. The flow begins with TripAdvisor review input, followed by preprocessing operations such as cleaning, normalization, and tokenization. After preprocessing, embeddings are generated and passed to the autoencoder and classification modules.",
        638: "The processed feature set then flows into the prediction stage, where machine learning models classify the review and generate related outputs. Finally, the results move to the evaluation and visualization stage, where the system produces graphs, metrics, and dashboard-based explanations. Thus, Fig. 4.1 represents both the architecture of the system and the data flow between its different modules. This stepwise flow is consistent with perturbation-analysis pipelines that move from raw text to representation-level and model-level reasoning [2], [18].",
        642: "This chapter explained the system design of the project using a single combined architecture figure. As shown in Fig. 4.1, the project follows a clear pipeline that begins with review collection and preprocessing, continues through embedding and feature extraction, and ends with prediction, evaluation, and visualization. This design supports both effective review analysis and easy interpretation of the final output [18], [19].",
        649: "This chapter explains how the proposed review analysis system was implemented. The implementation combines natural language processing, semantic embedding, anomaly-aware feature extraction, machine learning classification, rating prediction, and explainable AI techniques in a single pipeline. The complete system is designed to accept a review as input, process it step by step, classify it as clean or perturbed, predict the corresponding star rating, and provide explanation for the decision through an interactive dashboard. This overall implementation direction is aligned with recent adversarial and perturbation-aware text analysis research [1]-[3], [18].",
        667: "Once the semantic embedding is generated, it is passed through the autoencoder. The autoencoder is implemented using PyTorch and consists of an encoder and a decoder. The encoder compresses the embedding into a latent representation, and the decoder reconstructs the original embedding from this latent vector. The use of reconstruction behavior for anomaly-aware signals is consistent with recent autoencoder-centered detection literature [3], [7], [9].",
        675: "A unique part of this implementation is its focus on adverb-level analysis. The project uses spaCy to detect adverbs, negations, and intensifier-like words. In addition to part-of-speech detection, the system maintains a custom set of intensifiers such as “very,” “extremely,” “really,” “barely,” and “absolutely.” This combination of rule-based and linguistic detection helps the system capture words that may strongly influence sentence tone and prediction confidence. This is motivated by the broader adversarial literature showing that small token-level changes can strongly affect model behavior [10]-[17].",
        697: "The classification stage uses trained machine learning models to decide whether the review is clean or perturbed. The implementation supports multiple models, including Logistic Regression, Support Vector Machine, Random Forest, XGBoost, and LightGBM. These models are loaded from pre-trained .joblib files and used directly during inference. Using multiple models is useful because perturbation-aware analysis benefits from agreement comparison and robustness checking across classifiers [18], [19].",
        716: "The SHAP module is implemented to explain feature contribution for two main models: Logistic Regression and LightGBM. These two models were selected because they work well with the available feature types and support practical explanation behavior. In the broader context of this project, explanation is important because detection-only systems are often difficult to trust without feature-level justification [18], [19].",
        722: "The adverb ablation module is one of the core explanation components of the project. Its implementation is based on intervention rather than only attribution. The system removes each detected adverb one by one, recomputes the embedding and hybrid features, and reruns the selected models. It then compares the new probability with the original probability. This module operationalizes the same concern highlighted in adversarial text studies: even small wording changes can produce significant model shifts [10]-[17].",
        749: "To understand how the model behaves more generally, the project includes a global feature importance module. In this implementation, a sample of the dataset is selected, and feature values are permuted one by one. The drop in model accuracy caused by shuffling a feature is treated as a measure of that feature’s importance. This complements the local explanation methods and supports the broader trust goal of the project [18], [19].",
        755: "Confidence alone is not enough in a prediction system. A model may produce a high confidence value and still be wrong. Therefore, the project also implements calibration analysis. In this module, predictions over sampled data are grouped by confidence range, and the observed accuracy is compared with the predicted confidence. This is useful because current robustness literature stresses that reliability matters alongside raw accuracy [3], [18], [19].",
        775: "This chapter explained the implementation of the proposed system in detail. The project begins with text preprocessing and semantic embedding generation, then extracts anomaly-based and adverb-based hybrid features, and finally uses these features for classification and rating prediction. On top of the prediction pipeline, the system implements multiple XAI modules including SHAP, LIME, adverb ablation, counterfactual analysis, token attribution, PDP/ICE, global feature importance, and calibration. The complete implementation is therefore consistent with recent work that combines robustness, feature-space analysis, and interpretability for perturbed text [1]-[3], [18], [19].",
        801: "System testing is an important stage in the development of the project because it ensures that the implemented modules work correctly and produce meaningful outputs. Since the proposed system combines text preprocessing, semantic embedding, autoencoder-based anomaly detection, machine learning classification, star rating prediction, and explainable AI modules, testing must cover both the functional behavior of the system and the correctness of the generated outputs. This is especially important in perturbation-aware NLP systems, where robustness and interpretability must both be validated [18], [19].",
        1002: "This chapter presented the testing carried out for the proposed system. Functional testing confirmed that the system accepts valid review input and produces prediction outputs correctly. Autoencoder testing verified that anomaly-related features such as reconstruction error, latent distance, and anomaly score were computed successfully. Perturbation detection testing confirmed that adverb influence and dominant adverb logic worked as expected. Rating prediction testing verified that the star output was generated properly. Explainable AI testing showed that SHAP, LIME, counterfactual, token attribution, PDP/ICE, and calibration outputs were successfully displayed. Finally, integration testing confirmed that all modules worked together correctly in the Streamlit dashboard. This reinforces the project’s goal of combining robustness-aware review analysis with usable explanation support [18], [19].",
        1012: "This chapter presents the results obtained from the proposed review analysis system and explains the outputs generated by the dashboard. The project produces two categories of results. The first category includes model performance results such as accuracy, precision, recall, F1-score, ROC-AUC, and PR-AUC. The second category includes dashboard-based outputs such as prediction summaries, star-rating outputs, SHAP explanations, adverb ablation impact, counterfactual explanations, token attribution, PDP/ICE plots, global feature importance, and calibration curves. These outputs are important because modern perturbed-text systems must be evaluated not only by classification strength but also by transparency and trust [18], [19].",
        1018: "The results indicate that hybrid semantic and anomaly-aware features work effectively for perturbation detection. In particular, the high ROC-AUC and PR-AUC values suggest that the system can separate clean and perturbed samples well across threshold settings. This supports the broader literature that argues for multi-signal and feature-space approaches rather than single-signal detection [1]-[3].",
        1076: "The model agreement chart complements this summary by showing how many models classify the review as clean and how many classify it as perturbed. This is important because agreement across models increases trust in the final decision. If most models agree, the result appears more stable. If models disagree strongly, the user can interpret the prediction with more caution. Such stability concerns are central in perturbation-aware and adversarial robustness literature [18], [19].",
        1095: "This result is useful because it identifies which hybrid features contributed most to the final prediction. For some reviews, anomaly score or reconstruction error may dominate. For other reviews, adverb-based features such as adverb weight or average adverb influence may have stronger contribution. This makes SHAP one of the most important feature-level explanation outputs in the system, particularly when interpreted together with reconstruction-based detection ideas [3], [7], [9].",
        1102: "This output is especially useful because it provides intervention-based explanation instead of only feature attribution. Rather than only saying that an adverb-related feature is important, the system can show that removing a particular adverb causes a significant shift in probability. This helps identify the dominant adverb and connect model behavior directly to sentence meaning. The result is closely related to adversarial text findings showing that local wording changes can produce disproportionate model shifts [10]-[17].",
        1108: "The result is displayed as a table and a before-versus-after comparison. This is important because it answers a practical question: what should change in the review for the model to think differently? It also makes the explanation much easier to understand for non-technical users, since the modified sentence can be compared directly with the original one. The counterfactual output is shown in Fig. 7.5.",
        1120: "This output is useful because not all important tokens are adverbs. In some cases, content words, negations, or evaluative terms may strongly affect the prediction. Token attribution therefore gives another layer of explanation and helps detect whether the model depends too much on specific words. This is closely aligned with prior attack literature where token-level changes have a large effect on model outputs [10]-[17].",
        1147: "This result is valuable because it complements the local explanation methods. Instead of explaining only one review, it shows which features matter most more generally. If a feature such as anomaly score or adverb weight consistently causes a large accuracy drop when disturbed, that feature can be considered globally important. This supports the broader goal of robustness-aware interpretation [18], [19].",
        1153: "This is important because explanation alone is not enough if the confidence value is unreliable. Calibration gives an additional trust signal. In the current project, Logistic Regression and LightGBM calibration outputs are shown to help users judge how much the confidence scores should be trusted. This concern about reliability is consistent with recent adversarial defense discussions [3], [18], [19].",
        1163: "The dashboard outputs also show that the project goes beyond basic prediction. SHAP and LIME explain feature-level influence, adverb ablation explains intervention-level influence, counterfactuals explain how predictions can change, token attribution highlights important words, PDP/ICE explains feature sensitivity, global importance explains broader feature relevance, and calibration explains confidence reliability. This combination reflects the larger need for interpretable and trustworthy perturbed-text systems [18], [19].",
        1168: "This chapter presented the main results of the project. The performance table showed that the classification models achieved strong results, with LightGBM and Logistic Regression performing especially well. The dashboard outputs demonstrated that the system can explain predictions using multiple complementary methods. Together, these results confirm that the proposed system is effective for review perturbation detection, star rating prediction, and explainable AI based interpretation [1]-[3], [18], [19].",
        1191: "This chapter presents the conclusion of the project and discusses possible future improvements. The project was developed to address the problem of identifying whether a review is clean or perturbed while also predicting its star rating and explaining the reason behind the prediction. The system combines semantic embedding, anomaly-aware feature generation, machine learning prediction, and explainable AI into a single interactive dashboard. This direction is consistent with current research showing that robust text analysis requires more than simple classification and must account for perturbation, calibration, and interpretability [3], [7], [18].",
        1198: "The results show that the hybrid feature-based approach is effective for perturbation detection. The performance table indicates that models such as LightGBM and Logistic Regression perform especially well. More importantly, the explanation modules make the project stronger by showing which features or words influence the output the most. Among these, adverb ablation is a particularly useful contribution because it directly connects word-level changes to model-level probability shifts. This contribution fits well with recent literature on perturbed text, which emphasizes that small changes in wording can strongly affect classifier behavior [10]-[17].",
        1199: "Therefore, the project successfully achieves its aim of building a transparent, interpretable, and practical review analysis framework. It demonstrates that review classification can be made more meaningful when prediction is supported by explanation. Instead of only answering “what is the output?”, the project also answers “why was this output produced?” This aligns with the larger research direction of trustworthy NLP systems [18], [19].",
        1209: "Finally, future work can explore stronger robustness analysis by testing the system against more adversarially modified review inputs. This would help measure how well the hybrid features and explanation modules perform under deliberately crafted perturbations, especially against attack families discussed in the current literature [4], [10]-[17].",
        1210: "In summary, the current project provides a strong foundation for explainable review analysis, and there are several opportunities to improve it further in terms of dataset coverage, explanation quality, usability, and robustness [18], [19].",
    }.items():
        set_text(paragraphs[idx], text)

    files["word/document.xml"] = ET.tostring(doc, encoding="utf-8", xml_declaration=True)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    with ZipFile(OUT, "w", ZIP_DEFLATED) as zout:
        for name, data in files.items():
            zout.writestr(name, data)
    print(OUT)


if __name__ == "__main__":
    main()
